require(rms)
n <- 30
x1 <- runif(n)
x2 <- rnorm(n)
g  <- sample(letters[1:4], n, TRUE)
dd <- datadist(x1, x2, g); options(datadist='dd')

f <- ols(y ~ pol(x1, 2)*g + x2)
h <- ols(y ~ gTrans(x1, l=x, nl=x^2)*g + x2)
specs(h, long=TRUE)
rbind(coef(f), coef(h))
summary(f)
summary(h)
ggplot(Predict(f))
ggplot(Predict(h))

k1 <- list(x1=c(.2, .4), g='b')
k2 <- list(x1=c(.2, .4), g='d')
contrast(f, k1)
contrast(h, k1)
contrast(f, k1, k2)
contrast(h, k1, k2)

f <- ols(y ~ lsp(x1, c(.2, .4)))
h <- ols(y ~ gTrans(x1, l=x, nl=pmax(x - .2, 0), nl=pmax(x - .4, 0)))
rbind(coef(f), coef(h))
ggplot(Predict(f))
ggplot(Predict(h))
anova(f)
anova(h)

yl <- c(-0.25, 1.25)
h <- ols(y ~ gTrans(x1, x, x >= 0.2, pmax(x - .4, 0)))
ggplot(Predict(h), ylim=yl)
h <- ols(y ~ gTrans(x1, x, x >= 0.2, pmax(x - .2, 0), pmax(x - .4, 0)))
ggplot(Predict(h), ylim=yl)
h <- ols(y ~ gTrans(x1, x, x >= 0.2, pmax(pmin(x, 0.6) - .2, 0), pmax(pmin(x, 0.6)  - .4, 0)))
ggplot(Predict(h), ylim=yl)

z <- y ~ gTrans(x1, x, x >= 0.2, pmax(x - .2, 0), pmax(x - .4, 0))
h <- ols(update(z, ~. + x2))
ggplot(Predict(h))
